version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: testcontainer-01
    image: testimage:1.05
    ports:
    - "8080:8080"
    volumes:
    - myvol:/metro
    - /tetra:/femto
    networks:
    - mynet
volumes:
  myvol:
networks:
  mynet:
    driver: bridge
